# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blurImageProcessingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_blurImageProcessingWindow(object):
    def setupUi(self, blurImageProcessingWindow):
        blurImageProcessingWindow.setObjectName("blurImageProcessingWindow")
        blurImageProcessingWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(blurImageProcessingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 130, 221, 151))
        self.label.setObjectName("label")
        blurImageProcessingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(blurImageProcessingWindow)
        QtCore.QMetaObject.connectSlotsByName(blurImageProcessingWindow)

    def retranslateUi(self, blurImageProcessingWindow):
        _translate = QtCore.QCoreApplication.translate
        blurImageProcessingWindow.setWindowTitle(_translate("blurImageProcessingWindow", "模糊图像处理"))
        self.label.setText(_translate("blurImageProcessingWindow", "我是模糊处理界面"))
