# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'displayPicture.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_displayPictureWindow(object):
    def setupUi(self, displayPictureWindow):
        displayPictureWindow.setObjectName("displayPictureWindow")
        displayPictureWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(displayPictureWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditFileUrl = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditFileUrl.setGeometry(QtCore.QRect(10, 20, 601, 31))
        self.textEditFileUrl.setObjectName("textEditFileUrl")
        self.pushButtonChoiceFolder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonChoiceFolder.setGeometry(QtCore.QRect(640, 20, 101, 28))
        self.pushButtonChoiceFolder.setObjectName("pushButtonChoiceFolder")
        self.labelPicture = QtWidgets.QLabel(self.centralwidget)
        self.labelPicture.setGeometry(QtCore.QRect(190, 60, 360, 480))
        self.labelPicture.setText("")
        self.labelPicture.setObjectName("labelPicture")
        self.pushButtonPrevious = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPrevious.setGeometry(QtCore.QRect(80, 550, 93, 28))
        self.pushButtonPrevious.setObjectName("pushButtonPrevious")
        self.pushButtonNext = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNext.setGeometry(QtCore.QRect(570, 550, 93, 28))
        self.pushButtonNext.setObjectName("pushButtonNext")
        displayPictureWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(displayPictureWindow)
        QtCore.QMetaObject.connectSlotsByName(displayPictureWindow)

    def retranslateUi(self, displayPictureWindow):
        _translate = QtCore.QCoreApplication.translate
        displayPictureWindow.setWindowTitle(_translate("displayPictureWindow", "图片浏览"))
        self.pushButtonChoiceFolder.setText(_translate("displayPictureWindow", "选择文件夹"))
        self.pushButtonPrevious.setText(_translate("displayPictureWindow", "上一张"))
        self.pushButtonNext.setText(_translate("displayPictureWindow", "下一张"))
