# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'examPaperSettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_examPaperSettingWindow(object):
    def setupUi(self, examPaperSettingWindow):
        examPaperSettingWindow.setObjectName("examPaperSettingWindow")
        examPaperSettingWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(examPaperSettingWindow)
        self.centralwidget.setObjectName("centralwidget")
        examPaperSettingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(examPaperSettingWindow)
        QtCore.QMetaObject.connectSlotsByName(examPaperSettingWindow)

    def retranslateUi(self, examPaperSettingWindow):
        _translate = QtCore.QCoreApplication.translate
        examPaperSettingWindow.setWindowTitle(_translate("examPaperSettingWindow", "试卷设置"))
