# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gradingPaperWondow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gradingPaperWindow(object):
    def setupUi(self, gradingPaperWindow):
        gradingPaperWindow.setObjectName("gradingPaperWindow")
        gradingPaperWindow.resize(854, 637)
        self.centralwidget = QtWidgets.QWidget(gradingPaperWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidgetGrading = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetGrading.setGeometry(QtCore.QRect(20, 100, 781, 431))
        self.tableWidgetGrading.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetGrading.setAlternatingRowColors(True)
        self.tableWidgetGrading.setTextElideMode(QtCore.Qt.ElideLeft)
        self.tableWidgetGrading.setObjectName("tableWidgetGrading")
        self.tableWidgetGrading.setColumnCount(6)
        self.tableWidgetGrading.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetGrading.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetGrading.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetGrading.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetGrading.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetGrading.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidgetGrading.setHorizontalHeaderItem(5, item)
        self.tableWidgetGrading.horizontalHeader().setVisible(True)
        self.tableWidgetGrading.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetGrading.horizontalHeader().setHighlightSections(True)
        self.tableWidgetGrading.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetGrading.verticalHeader().setStretchLastSection(False)
        gradingPaperWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(gradingPaperWindow)
        QtCore.QMetaObject.connectSlotsByName(gradingPaperWindow)

    def retranslateUi(self, gradingPaperWindow):
        _translate = QtCore.QCoreApplication.translate
        gradingPaperWindow.setWindowTitle(_translate("gradingPaperWindow", "显示分数"))
        self.tableWidgetGrading.setSortingEnabled(False)
        item = self.tableWidgetGrading.horizontalHeaderItem(0)
        item.setText(_translate("gradingPaperWindow", "学号"))
        item = self.tableWidgetGrading.horizontalHeaderItem(1)
        item.setText(_translate("gradingPaperWindow", "姓名代码"))
        item = self.tableWidgetGrading.horizontalHeaderItem(2)
        item.setText(_translate("gradingPaperWindow", "单选成绩"))
        item = self.tableWidgetGrading.horizontalHeaderItem(3)
        item.setText(_translate("gradingPaperWindow", "多选成绩"))
        item = self.tableWidgetGrading.horizontalHeaderItem(4)
        item.setText(_translate("gradingPaperWindow", "总成绩"))
        item = self.tableWidgetGrading.horizontalHeaderItem(5)
        item.setText(_translate("gradingPaperWindow", "缺考"))
