# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gradingPaperWondow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gradingPaperWindow(object):
    def setupUi(self, gradingPaperWindow):
        gradingPaperWindow.setObjectName("gradingPaperWindow")
        gradingPaperWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(gradingPaperWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 200, 72, 15))
        self.label.setObjectName("label")
        gradingPaperWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(gradingPaperWindow)
        QtCore.QMetaObject.connectSlotsByName(gradingPaperWindow)

    def retranslateUi(self, gradingPaperWindow):
        _translate = QtCore.QCoreApplication.translate
        gradingPaperWindow.setWindowTitle(_translate("gradingPaperWindow", "MainWindow"))
        self.label.setText(_translate("gradingPaperWindow", "显示分数"))
