# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputAnswerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inputAnswerWindow(object):
    def setupUi(self, inputAnswerWindow):
        inputAnswerWindow.setObjectName("inputAnswerWindow")
        inputAnswerWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(inputAnswerWindow)
        self.centralwidget.setObjectName("centralwidget")
        inputAnswerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(inputAnswerWindow)
        QtCore.QMetaObject.connectSlotsByName(inputAnswerWindow)

    def retranslateUi(self, inputAnswerWindow):
        _translate = QtCore.QCoreApplication.translate
        inputAnswerWindow.setWindowTitle(_translate("inputAnswerWindow", "MainWindow"))
