# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inputReplyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inputReplyWindow(object):
    def setupUi(self, inputReplyWindow):
        inputReplyWindow.setObjectName("inputReplyWindow")
        inputReplyWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(inputReplyWindow)
        self.centralwidget.setObjectName("centralwidget")
        inputReplyWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(inputReplyWindow)
        QtCore.QMetaObject.connectSlotsByName(inputReplyWindow)

    def retranslateUi(self, inputReplyWindow):
        _translate = QtCore.QCoreApplication.translate
        inputReplyWindow.setWindowTitle(_translate("inputReplyWindow", "MainWindow"))
