# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menuWindow(object):
    def setupUi(self, menuWindow):
        menuWindow.setObjectName("menuWindow")
        menuWindow.resize(900, 732)
        self.centralwidget = QtWidgets.QWidget(menuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-2, -1, 901, 681))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageInputAnswer = QtWidgets.QWidget()
        self.pageInputAnswer.setObjectName("pageInputAnswer")
        self.stackedWidget.addWidget(self.pageInputAnswer)
        self.pageInputReply = QtWidgets.QWidget()
        self.pageInputReply.setObjectName("pageInputReply")
        self.stackedWidget.addWidget(self.pageInputReply)
        self.pageGradingPaper = QtWidgets.QWidget()
        self.pageGradingPaper.setObjectName("pageGradingPaper")
        self.stackedWidget.addWidget(self.pageGradingPaper)
        self.pageInitial = QtWidgets.QWidget()
        self.pageInitial.setObjectName("pageInitial")
        self.stackedWidget.addWidget(self.pageInitial)
        menuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        menuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menuWindow)
        self.statusbar.setObjectName("statusbar")
        menuWindow.setStatusBar(self.statusbar)
        self.actionInputAnswer = QtWidgets.QAction(menuWindow)
        self.actionInputAnswer.setObjectName("actionInputAnswer")
        self.actionInputReply = QtWidgets.QAction(menuWindow)
        self.actionInputReply.setObjectName("actionInputReply")
        self.actionGradingPaper = QtWidgets.QAction(menuWindow)
        self.actionGradingPaper.setObjectName("actionGradingPaper")
        self.menu.addAction(self.actionInputAnswer)
        self.menu.addAction(self.actionInputReply)
        self.menu.addAction(self.actionGradingPaper)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(menuWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(menuWindow)

    def retranslateUi(self, menuWindow):
        _translate = QtCore.QCoreApplication.translate
        menuWindow.setWindowTitle(_translate("menuWindow", "MainWindow"))
        self.menu.setTitle(_translate("menuWindow", "菜单"))
        self.actionInputAnswer.setText(_translate("menuWindow", "读入答案"))
        self.actionInputReply.setText(_translate("menuWindow", "读入试卷"))
        self.actionGradingPaper.setText(_translate("menuWindow", "开始阅卷"))
