# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perspectiveTransformationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_perspectiveTransformationWindow(object):
    def setupUi(self, perspectiveTransformationWindow):
        perspectiveTransformationWindow.setObjectName("perspectiveTransformationWindow")
        perspectiveTransformationWindow.resize(802, 710)
        self.centralwidget = QtWidgets.QWidget(perspectiveTransformationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(10, 30, 701, 261))
        self.label2.setStyleSheet("font: 28pt \"微软雅黑\";\n"
"font: 18pt \"Adobe Devanagari\";\n"
"font: 14pt \"Adobe Devanagari\";")
        self.label2.setObjectName("label2")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 290, 111, 16))
        self.label1.setObjectName("label1")
        self.lineEditBasicParameterAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditBasicParameterAddress.setGeometry(QtCore.QRect(120, 290, 541, 21))
        self.lineEditBasicParameterAddress.setObjectName("lineEditBasicParameterAddress")
        self.pushButtonBasicParameterChoice = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBasicParameterChoice.setGeometry(QtCore.QRect(700, 290, 51, 20))
        self.pushButtonBasicParameterChoice.setStyleSheet("background-color: rgb(177, 177, 177);")
        self.pushButtonBasicParameterChoice.setObjectName("pushButtonBasicParameterChoice")
        self.labelBasicParameterImage = QtWidgets.QLabel(self.centralwidget)
        self.labelBasicParameterImage.setGeometry(QtCore.QRect(420, 360, 240, 320))
        self.labelBasicParameterImage.setStyleSheet("# labelBasicParameterImage{\n"
"rgb(255, 255, 127)}")
        self.labelBasicParameterImage.setText("")
        self.labelBasicParameterImage.setObjectName("labelBasicParameterImage")
        self.pushButtonStartAdjust = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStartAdjust.setGeometry(QtCore.QRect(680, 330, 93, 28))
        self.pushButtonStartAdjust.setObjectName("pushButtonStartAdjust")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 340, 72, 15))
        self.label.setObjectName("label")
        self.labelOriginalBasicParameterImage = QtWidgets.QLabel(self.centralwidget)
        self.labelOriginalBasicParameterImage.setGeometry(QtCore.QRect(60, 360, 240, 320))
        self.labelOriginalBasicParameterImage.setStyleSheet("# labelBasicParameterImage{\n"
"rgb(255, 255, 127)}")
        self.labelOriginalBasicParameterImage.setText("")
        self.labelOriginalBasicParameterImage.setObjectName("labelOriginalBasicParameterImage")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 340, 72, 15))
        self.label_2.setObjectName("label_2")
        perspectiveTransformationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(perspectiveTransformationWindow)
        QtCore.QMetaObject.connectSlotsByName(perspectiveTransformationWindow)

    def retranslateUi(self, perspectiveTransformationWindow):
        _translate = QtCore.QCoreApplication.translate
        perspectiveTransformationWindow.setWindowTitle(_translate("perspectiveTransformationWindow", "透视变换"))
        self.label2.setText(_translate("perspectiveTransformationWindow", "1、由于照片的差异，需要手动调整一些参数，帮助系统更好的运行。\n"
"2、强度梯度小于minThresh的必定不是边缘\n"
"3、强度梯度大于maxThresh的必定是边缘\n"
"4、dilate会连接不连续部分\n"
"5、erode会丢弃边缘部分的像素，可能会造成不连续\n"
"6、请随机选择一批图片中的一张\n"
"7、点击Esc退出settings界面\n"
""))
        self.label1.setText(_translate("perspectiveTransformationWindow", "选择样例图片："))
        self.pushButtonBasicParameterChoice.setText(_translate("perspectiveTransformationWindow", "..."))
        self.pushButtonStartAdjust.setText(_translate("perspectiveTransformationWindow", "开始调整"))
        self.label.setText(_translate("perspectiveTransformationWindow", "处理结果："))
        self.label_2.setText(_translate("perspectiveTransformationWindow", "原图："))
